[passwords]
david_scatterday = "abc123"
mike = "prointel1"
adam = "prointel2"
joe = "abc123"

[connections.mysql]
dialect = "mysql"
driver = "pymysql"  # Must match installed driver
host = "sql.freedb.tech"
port = 3306
database = "freedb_NYCtest"
username = "freedb_davidscatterday"
password = "KC55*RM*F8ujyfn"

