[passwords]
david_scatterday = "abc123"
mike = "prointel1"
adam = "prointel2"
[connections.mysql]
dialect = "mysql"
driver = "pymysql"
host = "sql.freedb.tech"
port = 3306
username = "freedb_davidscatterday"
password = "KC55*RM*F8ujyfn"
database = "freedb_NYCtest"